AWSTemplateFormatVersion: "2010-09-09"
Description: >
  A VPC

Parameters:
  AppName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: camel-backend
  VpcCIDR:
    Description: VPC CIDR that will be prefixed to resource names
    Type: String
    Default: ''

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Ref AppName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-IG

  InternetGatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref VPC
    Export:
      Name: !Sub "${AppName}-VPC"

  InternetGateway:
    Value: !Ref InternetGateway
    Export:
      Name: !Sub "${AppName}-InternetGateway"
